alice-doc/alice-analysis-tutorial

- SUMMARY.md
- analysis/ROOT5-to-6.md
Basic howto as help for people needing to move from
ROOT5 to ROOT6, listing the main differences. Section
within the tutorial page yet to be specified.
> Add tutorial for the transition from ROOT5 to ROOT6

- SUMMARY.md
- book.json
- building/README.md
- building/prereq-macos.md
- building/prereq-ubuntu.md
- css/website.css
This PR will be used to keep track of our new, revamped, aliBuild documentation. As soon as it's in `[WIP]` (as in Work In Progress state) it must not be merged.
Any comment is appreciated!
> Add aliBuild documentation

- building/prereq-ubuntu.md
Thanks to @cnattras for testing them!
> Fix Ubuntu 18.04 instructions

- building/README.md
- building/prereq-centos7.md
- building/prereq-fedora.md
- building/prereq-macos.md
- building/prereq-ubuntu.md
> Add Docker instructions

- building/README.md
Add the use of `-z <blah>` to aliBuild
> Fix problem in using ROOT5/6 at the same time

- building/prereq-centos7.md
- building/prereq-fedora.md
- building/prereq-ubuntu.md
I have no macOS machine, but unzip package seems to exist for Homebrew according to the web. Please check if the package is really installable before merging, if anyone has Mac.
> Add unzip(1) to the prerequisites.

- building/alidock.md
the 'cleanup' command doesn't exist, it should be 'clean'
> Fix command syntax

- .travis.yml
- building/prereq-centos7.md
If a command is wrong in the prerequisites, the PR will fail. We do not need to
perform the same lengthy test during the page generation phase (master Travis
build)
> Check for prerequisite cmds in PRs, not branches

- rivet/advanced-topics.md
Hello,
I have updated the section about "advanced topics" for the local installations of Rivet and now as well about the MC generators.
@mpuccio @pkarczma : are you the ones to review this kind of input ?
Cheers,
Antonin
> Rivet - Update of "advanced topics" (local installations)

- analysis/alianalysistaskmytask.md
minor: brought down }; from the commented line in analysis/alianalysistaskmytask.md
> minor: brought down }; 

- rivet/references.md
Clean the reference page + add a few recent entries
> Rivet - update references.md

- building/prereq-macos.md
Add a statement on the new ARM powered Macs and update macOS documentation.
> [macOS] Statement on Apple Silicon

- building/custom.md
Removing Ubuntu 16.04 as suggested by @vkucera 
Updating OSX list: @pzhristov @ktf here I need your wisdom
> Update OS list

- building/build.md
Ciao @vkucera,
I slightly modified your instructions to make the command copy-pasteble (what I do usually, because I am lazy).
Can you bless/comment?
Thanks a lot!
Cheers,
Max
> Make the find command usable by just copy-paste

- README.md
- building/build.md
- building/devel.md
Related PRs:
* https://github.com/alisw/alibuild/pull/691
* https://github.com/alisw/alisw.github.io/pull/97
> Use standard names of remotes.

- analysis/hints.md
- analysis/streamer.md
- analysis/trouble.md
> Remove obsolete links

- building/prereq-ubuntu.md
Apparently this is required to compile ONNXRuntime with the system python
> Add python3-dev as system package

- building/prereq-ubuntu.md
> Install python3-pip on Ubuntu

- building/build.md
This is now the default, so no need to specify it any more.
@ktf @ddobrigk
> Remove explicit o2 defaults

- building/prereq-macos.md
This has been fixed for a while, with an update of ROOT.
> Xcode 14.3 works again

- building/custom.md
- building/prereq-ubuntu.md
Ubuntu 24.04 is now supported
https://its.cern.ch/jira/browse/O2-5108
> Add Ubuntu 24.04 support
