analysis/ROOT5-to-6.md
analysis/bonus.md

Page header was removed by mistake and therefore not highlighted in the current version

Fix broken page headline

---

building/prereq-macos.md

No longer necessary: instructions updated to explain how to revert the old
workaround too.

Remove Homebrew automake workaround

---

building/prereq-centos7.md

Picking latest version conflicts with system's pyparsing

Pinpoint matplotlib version on CC7

---

building/alidock.md
start/README.md

* Add missing `--user` to `pip3 install` where appropriate
* Fix the subscription policy for the mailing lists

Fix pip3 for alidock and subscription

---

building/build.md

I was helping a new member of our group, and noticed that `install` was missing from the line to rebuild AliPhysics.
I still haven't switched to alidock, so it's possible that I've missed some underlying reason why this isn't required (if so, please close and disregard), but otherwise, I think calling `make install` is required - it appear to fix the issue in our case

Add missing "install"

---

building/prereq-macos.md

Since anyway a specific version is required by alidist and sometimes brew's boost breaks aliBuild's, let's remove boost from the requirements.

Remove boost from the pre-req on mac

---

.gitignore
building/README.md

As discussed in the WP3, remove the strong wording towards alidock. For O2 developers, including the detectors people, it is usually better to use alibuild on their system. In particular, it allows to use the DPL gui.
I took the opportunity to simplify the page. 
If it seems too confusing, I would propose to have a simple table assessing which features each option has.

Remove preferred building option for ALICE

---

building/prereq-centos7.md

tk-devel is necessary to build python3

Add tk-devel to the dependencies of CC7

---

building/prereq-centos7.md
building/prereq-fedora.md
building/prereq-macos.md
building/prereq-ubuntu.md

I reviewed the prerequisites for installing ALICE O2 on the different platforms. Using containers I verified that the installation of the prerequisites works and that `aliDoctor` does not complain on all of the listed platforms and OS versions.
Asking for a review

Update Prerequisites for Different Platforms

---

building/prereq-macos.md

Since ROOT needs `LD_LIBRARY_PATH` for loading dynamic libraries which is not propagated with SIP disabled, we need to ask users to switch off SIP on their machines.

Require SIP disabled for macOS

---

building/prereq-centos7.md
building/prereq-ubuntu.md

* Adding dependencies for Ubuntu 18.04: libglfw3-dev libglfw3
* Adding dependecy for CentOS 7: glfw-devel
See https://alice-talk.web.cern.ch/t/building-o2-fails-in-debuggui/444

Adding GFLW as dependency for Ubuntu 18.04 and CentOS 7

---

analysis/MC.md
analysis/grid.md
analysis/rungrid.md
analysis/setup.md
start/cert.md

Adding JAliEn and alien.py related updates. Mostly notes that alien-token-init is now optional, and switch from aliensh to alien.py.

Add information about JAliEn and alien.py

---

SUMMARY.md
analysis/oadb.md

Add a short section on the OADB; text is basically copied from the ALICE github docbook https://alisw.github.io/git-advanced/, which is however difficult to find for an unsuspecting user. Would suggest that we keep and grow this piece of documentation here.

Add OADB discussion from alice github docbook

---

building/prereq-ubuntu.md

On Ubuntu 20.04 the compilation of DebugGUI fails without the package with the following error message:
Resolving dependencies of ../../../server/TracyWorker.cpp
In file included from /usr/include/c++/9/pstl/parallel_backend.h:14,
from /usr/include/c++/9/pstl/algorithm_impl.h:25,
from /usr/include/c++/9/pstl/glue_execution_defs.h:52,
from /usr/include/c++/9/execution:32,
from ../../../server/TracySort.hpp:7,
from ../../../server/TracyWorker.cpp:27:
/usr/include/c++/9/pstl/parallel_backend_tbb.h:28:2: error: #error Intel(R) Threading Building Blocks 2018 is required; older versions are not supported.
28 | #error Intel(R) Threading Building Blocks 2018 is required; older versions are not supported.
|  ^~~~~
Installing libtbb-dev solved the issue for me. Otherwise a fix described in …

Add libtbb-dev, required for building DebugGUI on Ubuntu 20

---

building/prereq-ubuntu.md

I propose a cleanup for the Ubuntu prerequisites page: 
* Remove `Ubuntu 16.04` instructions as they don't work: `scipy` needs `python 3.6` but `16.04` comes with `python 3.5.4` and thus `python-modules` fail. So it's better to remove the instructions. If someone wants to use `16.04` they can figure out themselves.
* Updated instructions for `Ubuntu 18.04` and `20.04`:  removed `cmake` as we always use a more recent version and `libyaml-cpp-dev` as it fails to build with `20.04`. Add  `libtbb-dev`,  `python3-venv` and `libncurses-dev` to compile with `20.04`. Tested both `18.04` and `20.04` in docker containers to simulate a fresh install.

O2-1802 [Ubuntu] instructions for 20.04, removed 16.04

---

rivet/advanced-topics.md

Update the installation content to keep it in line with aliBuild standards.
(Got a question about this, this morning during the Rivet workshop, 2020-11-18)

Rivet tuto (advanced-topics) - installation update

---

.github/workflows/main.yml

Need to bump action version because of deprecation of `set-env` _et similia_ in GHA runners.
For instance, latest PR: https://github.com/alice-doc/alice-analysis-tutorial/pull/115 failed because of that.
A bump to v3.7.1 should fix it, see: https://github.com/JamesIves/github-pages-deploy-action/issues/500

Bump GH-Pages deployment

---

building/prereq-ubuntu.md

Package `unzip` is twice in the list. Doesn't hurt using apt, but puppet complains when I want to use this list so I removed the duplicate.

Remove duplicate in ubuntu prerequisites

---

building/prereq-centos7.md

Advantages of this approach:
* Allows unification different build instructions / recipes and use .
* We can update the installation of new tools and simply ask people to yum update.
* Shorter instructions.

Use meta RPM package to install dependencies

---

building/prereq-macos.md

We have everything in place to support SIP enabled installations. If it does not work, we should fix it.

Drop the need to disable SIP

---

building/custom.md

Maybe such a change is needed (pip -> pip3).
At least seems necessary under Ubuntu 18.04 LTS.

Build tutorial - update from pip to pip3 ?

---

building/prereq-centos7.md

Since we now require GCC 10.2, which is not available as DevToolsSet, these instructions are not valid anymore.

Drop DevToolsSet from instructions

---

building/custom.md
building/prereq-centos7.md
building/prereq-centos8.md
building/prereq-fedora.md
building/prereq-macos.md
building/prereq-ubuntu.md

* Use distribution packages for aliBuild installation where available.
* Keep `pip` as a special case.

Simplify build instructions

---

building/prereq-centos7.md

This is required because if we do it in one go, EPEL and the required python3 packages required by aliBuild will not yet be available.

Make sure we have EPEL packages available

---

building/prereq-macos.md

A note has been added about ALICE software not compiling under macOS Monterey.

[macOS] note about macOS Monterey

---

building/prereq-ubuntu.md

For Ubuntu (at least my Kubuntu 20.04 LTS), I do not succeed to use "alibuild deps" to create graphs dependencies since quite some time.
6 amaire-sbgat92: AliceSuite >aliBuild deps YODA --defaults generators --outgraph test.pdf
ERROR: Error generating dependencies with dot: FileNotFoundError: [Errno 2] No such file or directory: 'dot'
I have just figured out that my system miss a needed system package : python3-pydot
I updated here the apt install command to include such an extra package

aliBuild prerequisite for Ubuntu - Need "python3-pydot"

---

analysis/ROOT5-to-6.md
building/build.md

This PR cleans up the remaining `aliBuild --defaults` options mentioned in the tutorial.
Cc: @pzhristov

Always build AliPhysics with `o2` defaults

---

building/prereq-ubuntu.md

Building on Ubuntu 22.04 requires also installing `gtk-doc-tools`. The package is not needed on earlier Ubuntu versions but it is available, so I decided to not split the prerequisite list.

Update prerequisites for Ubuntu 22.04

---

building/prereq-macos.md

Xcode 14.3 is broken, so call that out specifically.
Also, remove the old `PATH=/usr/local/...` line, since that doesn't do anything on newer MacOS versions (where Homebrew installs itself into /opt/homebrew), and it doesn't seem to be required.
Add instructions to set up Homebrew properly instead.
Also, add a note about package versions: Brew sometimes installs newer versions of some packages (like llvm or python) in parallel with the officially supported ones.

Add current caveats for MacOS setup

---

building/custom.md

We support Alma 8 as the "official" CentOS replacement. Also add newer Ubuntu and MacOS versions.

Update list of supported OS versions

---

building/prereq-macos.md

Some users have pre-existing ROOT installations, and this often causes problems when compiling O2/O2Physics.

Add instructions on uninstalling non-ALICE ROOT installations

---

building/prereq-alma9.md

Some required development tools aren't available in the default repos any more, so the "CRB" (formerly "PowerTools") repo needs to be enabled on Alma 9.

Document required development tools repo on Alma 9

---

SUMMARY.md
building/custom.md
building/manual-install.md

The manual installation instructions seems to trip people up.
Make it clearer that the per-OS instructions are the recommended ones, and link to the "advanced" installation instructions on a separate page.

De-emphasise manual installation of aliBuild
